# Generated by Django 4.1 on 2022-08-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_scope_article_alter_scope_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="scope",
            options={"ordering": ["-tag"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Раздел",
                "verbose_name_plural": "Разделы",
            },
        ),
    ]
