# Generated by Django 4.1 on 2022-08-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_options_alter_scope_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scope",
            options={"ordering": ["is_main", "tag"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Раздел", "verbose_name_plural": "Разделы"},
        ),
    ]
