# Generated by Django 4.1 on 2022-08-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_auto_20220821_1735"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
    ]
